name: Create only instance and test with Buildout

on: push

jobs:
  build:
    strategy:
      matrix:
        python-version:
        # Use the oldest supported Python version, as that may pull in more versions.
        - "3.7"
    runs-on: ubuntu-latest
    steps:
    - name: locale
      # needed for CMFPlone testUnicodeSplitter test
      run: |
        sudo locale-gen nl_NL@euro
        sudo update-locale
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install Python dependencies (pip)"
      uses: "py-actions/py-dependency-install@v2"
      with:
        path: "requirements.txt"
        update-setuptools: "false"
        update-pip: "true"
        update-wheel: "true"
    - name: Cache eggs
      uses: actions/cache@v2
      with:
        path: |
          eggs
        key: eggs-${{ hashFiles('**/*.cfg') }}
        restore-keys: eggs-
    - name: Run buildout
      run: |
        buildout -c bare.cfg buildout:git-clone-depth=1
    - name: Quickly run unit tests without any layers
      run: |
        bin/test -u
